# Generated by Django 3.0.5 on 2020-05-03 12:37

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200503_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
