# Generated by Django 3.0.5 on 2020-05-24 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
