# Generated by Django 3.0.5 on 2020-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200529_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-date', 'pk']},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.URLField(null=True),
        ),
    ]
