# Generated by Django 3.0.5 on 2020-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200614_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='issue',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='../media/issue_media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(null=True, upload_to='../media/project_media/logo'),
        ),
    ]
