# Generated by Django 3.0.5 on 2020-06-23 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20200617_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(null=True, related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
