# Generated by Django 3.0.5 on 2020-06-23 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200623_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
