# Generated by Django 3.0.5 on 2020-07-25 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200725_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
