# Generated by Django 3.0.5 on 2020-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20200725_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
