# Generated by Django 3.0.5 on 2020-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20200726_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
