# Generated by Django 3.0.5 on 2020-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20200726_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='./issue_media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(null=True, upload_to='./project_media/logo'),
        ),
    ]
